### ISSUE TITLE
script not selecting bottom option

### ISSUE THREAD

**Issue by Losif-kun** [1hubert/genshin-dialogue-autoskip#1]
The script is not clicking

**Comment by Vamqueror** [comment]
I don't know if its still relevant to you but I fixed this issue. 
hopefully the author is active and will accept my pull request.

in the meantime you can clone working forked version here :https://github.com/Vamqueror/genshin-dialogue-autoskip

**Comment by 1hubert** [comment]
Hi @Losif-kun, I've just accepted the pull request by Vamqueror which will probably fix you issue!

If you still can't get the script to click, make sure to:
1) Run the script with admin privileges - A simple way to do it is right-clicking the handy `run.bat` file by Vamqueror and selecting "Run as administrator"
2) If you haven't already, press F8 on your keyboard to start the main loop after you run the script.
