### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by landerlive47** [1hubert/genshin-dialogue-autoskip#11]
Nothing happens when it runs. Only sound on start? that new device connected.

**Comment by 1hubert** [comment]
Have you run the `run.bat` file as admin? And then pressed F8?

**Comment by 1hubert** [comment]
Hey @landerlive47, has your issue been resolved? 🙂

**Comment by Siffz** [comment]
it says that 'py' is not recognized as internal or external command , operable program or batch file.

**Comment by 1hubert** [comment]
So you don't Python installed? Let me guide you through the process from the beginning to the end:
1) Download Python here: https://www.python.org/downloads/
2) Install Python and make sure that the "add to PATH" checkbox is checked
3) Download `genshin-dialogue-autoskip` as zip, unpack
4) Inside of the `genshin-dialogue-autoskip` folder, open cmd and run `pip install -r requirements.txt`
5) Now run the `run.bat` file as admin and it should work properly

**Comment by 1hubert** [comment]
Let me know if that worked for you 🙂

**Comment by Siffz** [comment]
Hi yeah somehow I can't Install the python I think my PC has a problem so I
will stop trying for now but thanks for Your help

**Comment by 1hubert** [comment]
As you wish! Have a nice day.
