### ISSUE TITLE
ModuleNotFoundError: No module named 'vgamepad' after installing vgamepad

### ISSUE THREAD

**Issue by MercfifulZephyr** [1hubert/genshin-dialogue-autoskip#16]
Just downloaded this script and tried to run it but get this error every time. I installed the contents of the requirements.txt file successfully with pip. I tried restarting and moving the script to my C drive, but it still gets the same error. Sorry if this is a dumb question, I don't really know anything about coding.

C:\Windows\system32>pushd "D:\Toolkit\Mirror\Desktop\Applications\Scripts\genshin-dialogue-autoskip-main\"

D:\Toolkit\Mirror\Desktop\Applications\Scripts\genshin-dialogue-autoskip-main>py ./autoskip_dialogue.py
Traceback (most recent call last):
  File "D:\Toolkit\Mirror\Desktop\Applications\Scripts\genshin-dialogue-autoskip-main\autoskip_dialogue.py", line 5, in <module>
    import vgamepad as vg
ModuleNotFoundError: No module named 'vgamepad'

**Comment by 1hubert** [comment]
If you don't need the gamepad support, you might try an older version of the script where there's no `vgamepad` dependency which seems to be problematic for a lot of folks.

Here's the direct link to that version: https://github.com/1hubert/genshin-dialogue-autoskip/archive/66376a7c6f8f1b09874e2ff962fb9300756b4d10.zip

**Comment by MercfifulZephyr** [comment]
I downloaded the linked file above and tried to run the .bat with admin privileges but got this error.

ModuleNotFoundError: No module named 'pyautogui'

I ran pip install pyautogui in cmd prompt to double check that I had it and got a whole bunch of requirement already satisfied messages, still can't get it to work.

**Comment by MercfifulZephyr** [comment]
Think I got it to work by opening the folder with the script, then pressing alt+f+s+a to open an admin cmd in that folder then running python3 autoskip_dialogue.py. I think I also might've misunderstood the effects of the script, as it seems to let dialogue play out instead of spamming click through it. Is that the intended function of the script or is it just not working for me? The auto selecting the bottom choice does work though.

**Comment by 1hubert** [comment]
Glad you figured it out.

> I think I also might've misunderstood the effects of the script, as it seems to let dialogue play out instead of spamming click through it. Is that the intended function of the script or is it just not working for me? The auto selecting the bottom choice does work though.

No, you didn't misunderstand, there was a bug in the version I provided you. Sorry!

I've created a new branch just for keyboard and mouse users, this version is proven to work without issues: https://github.com/1hubert/genshin-dialogue-autoskip/tree/kbm_only

In the `kbm_only` branch version both auto-selects bottom choice and spam-clicks through the dialogue, tested it today and works ok.

**Comment by MercfifulZephyr** [comment]
I tried the new branch and got it to work. Figured out that you have to start Genshin before starting the script for it work. It also seems that if you have autoplay on, the auto select bottom choice works while the spam clicks doesn't, but with autoplay off, both work. Thanks for the help!
