### ISSUE TITLE
1366x768 support

### ISSUE THREAD

**Issue by e1uone** [1hubert/genshin-dialogue-autoskip#17]
Hi, thanks for the script. Here is a modified values that works for me on 1366x768 dispaly

BOTTOM_DIALOGUE_MIN_X = 921 
BOTTOM_DIALOGUE_MAX_X = 1237
BOTTOM_DIALOGUE_MIN_Y = 553 
BOTTOM_DIALOGUE_MAX_Y = 583 

PLAYING_ICON_X = 48
PLAYING_ICON_Y = 21

DIALOGUE_ICON_X = 921
DIALOGUE_ICON_LOWER_Y = 574
DIALOGUE_ICON_HIGHER_Y = 562

LOADING_SCREEN_X = 1200
LOADING_SCREEN_Y = 700

**Comment by 1hubert** [comment]
Hey @e1uone

If you ever upgrade to a higher res screen, the lastest version of the script auto-detects your resolution and adjusts the uppercase variables.
Direct link: https://github.com/1hubert/genshin-dialogue-autoskip/archive/refs/heads/main.zip

The first time you'll run the `run.bat` file, it will auto-detect your screen resolution and ask for confirmation. After you confirm it's the correct resolution, it will be stored in `.env` file.

Have a nice day.
