### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by Vockorc** [1hubert/genshin-dialogue-autoskip#21]
hi im getting this issue

any idea what could be causing this ?

Thank you!

![Capture](https://github.com/1hubert/genshin-dialogue-autoskip/assets/147757733/c5c49274-a16a-4230-ae9f-0898263b4bce)

**Comment by 1hubert** [comment]
hello, unfortunately I've never encountered this issue before so I don't have a quick way to solve it.

my guess is that something external is forcibly killing the python process right as it starts up. may be windows defender or other antivirus. you could try disabling them and see if that helps

other than that, you could:
- restart your pc
- make sure you're running the `run.bat` as admin
- install dependencies from the `requirements.txt` file to make sure you have them on versions that are proven to work 
- reinstall python

**Comment by 1hubert** [comment]
has any of that helped?

**Comment by 1hubert** [comment]
This error is fixed in the newest version of the script (tested with Python 3.12) ! 🎉

Just make sure to install every Python module with `pip install -r requirements.txt".

Let me know is it working for you! 🙂
