### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rafix000** [1hubert/genshin-dialogue-autoskip#23]
ModuleNotFoundError: No module named 'win32api'

**Comment by 1hubert** [comment]
1) click the windows button
2) type `cmd`
3) run this command: `pip install pywin32`

**Comment by 1hubert** [comment]
My last message probably didn't help.

This error is affecting users of the newest version of Python (3.12). I'm pretty sure downgrading to Python 3.10.5 will let you use the script for now while I figure out what's going on.

You can download Python 3.10.5 here:
https://www.python.org/downloads/release/python-3105

**Comment by 1hubert** [comment]
This error is fixed in the newest version of the script (tested with Python 3.12) ! 🎉

Just make sure to install every Python module with `pip install -r requirements.txt".

Let me know is it working for you! 🙂
