### ISSUE TITLE
win32api import issue

### ISSUE THREAD

**Issue by Zlreael** [1hubert/genshin-dialogue-autoskip#24]
![cmd_ys4eAklKto](https://github.com/1hubert/genshin-dialogue-autoskip/assets/148623398/94a57412-3307-4a00-90af-a8d24c593818)

**Comment by 1hubert** [comment]
1) click the windows button
2) type `cmd`
3) run this command: `pip install pywin32`

**Comment by Zlreael** [comment]
I allready did that. I tried reinstalling it.
https://i.imgur.com/h5EJTls.png
Im not versed in python but it might be the version.
Thanks for any help.

**Comment by 1hubert** [comment]
You're right, the `ModuleNotFoundError: No module named 'win32api'` is related to Python's version.

I just got it too after upgrading from Python `3.10.5` to `3.12`.

Fixing this error is now a priority. I'll get back to you when I figure it out.

**Comment by 1hubert** [comment]
For now, to get the script to work you can download Python `3.10.5` from here:
https://www.python.org/downloads/release/python-3105

**Comment by 1hubert** [comment]
This error is fixed in the newest version of the script (tested with Python 3.12) ! 🎉

Just make sure to install every Python module with `pip install -r requirements.txt".

Let me know is it working for you! 🙂
