### ISSUE TITLE
what to change to switch from k&m to controller

### ISSUE THREAD

**Issue by IlMidolI** [1hubert/genshin-dialogue-autoskip#25]
what "main" named script should you change to switch from default keyboard and mouse to controller please?

**Comment by 1hubert** [comment]
![image](https://github.com/1hubert/genshin-dialogue-autoskip/assets/51206366/6922a865-cc60-48d4-9bbb-90359222d19b)

**Comment by 1hubert** [comment]
I'm not even sure if the gamepad_only version works, as the gamepad-specific code was created by someone else. I don't own any gamepads myself and can't test it.
