### ISSUE TITLE
Can't run program

### ISSUE THREAD

**Issue by LightHillNess** [1hubert/genshin-dialogue-autoskip#27]
I installed everything from requirments.txt 
and when I try to run run.bat 
I get this 

Welcome to Genshin Impact Dialogue Skipper

Traceback (most recent call last):
  File "D:\genshinskip\autoskip_dialogue.py", line 19, in <module>
    if os.environ['WIDTH'] == '' or os.environ['HEIGHT'] == '':
       ~~~~~~~~~~^^^^^^^^^
  File "<frozen os>", line 685, in __getitem__
KeyError: 'WIDTH'
Press any key to continue . . .

**Comment by 1hubert** [comment]
In theory, the program should auto-detect your resolution, ask you if it's correct, and save it in `.env` file.

Open the `.env` file with windows notepad and type in your monitor resolution like this:

```
WIDTH=1920
HEIGHT=1080
```

Hope that helps! Happy holidays!

**Comment by LightHillNess** [comment]
No this didn't help. Happy  holidays!

**Comment by 1hubert** [comment]
Try replacing line 19 with this:
`if os.getenv('WIDTH') == '' or os.getenv('HEIGHT') == '':
`

**Comment by LightHillNess** [comment]
![image](https://github.com/1hubert/genshin-dialogue-autoskip/assets/104416322/8168140d-c327-4c60-95cd-a0348629664e)

**Comment by 1hubert** [comment]
I get the same error after deleting my `.env` file. It has to be present in the same folder as `autoskip_dialogue.py` and `run.bat`. If you're sure it's there, then sorry, but I'm not able to reproduce your error and can't help you :(

**Comment by LightHillNess** [comment]
I fixed the problem when I downloaded the file it was env.txt  changed it to .env now it works thanks

**Comment by 1hubert** [comment]
That's great to hear!
