### ISSUE TITLE
help, line 19 error

### ISSUE THREAD

**Issue by deka123A** [1hubert/genshin-dialogue-autoskip#33]
Traceback (most recent call last):
  File "C:\Users\adeka\autoskip_dialogue.py", line 19, in <module>
    if os.environ['WIDTH'] == '' or os.environ['HEIGHT'] == '':
       ~~~~~~~~~~^^^^^^^^^
  File "<frozen os>", line 685, in __getitem__
KeyError: 'WIDTH'

**Comment by 1hubert** [comment]
hello!

there's an issue where github changes `.env` into `env.txt`, when downloaded as an individual file.

it's supposed to be called `.env`

it's a file that initially looks like this (when opened with windows notepad):
```
WIDTH=
HEIGHT=
```

But after successfuly running the script for the first time, it stores your auto-detected screen resolution, in my case:
```
WIDTH=1920
HEIGHT=1080
```

so, make that there's a `.env` file in the same directory as `autoskip_dialogue.py`, and if there isn't, rename `env.txt` -> `.env` (if it exists) or create a new `.env` file yourself, adhoring to the template i've described above.

**Comment by deka123A** [comment]
it worked thanks so much!

I need to clarify something, to your program to run successfully I need the "auto" at the left up turn on right?

**Comment by 1hubert** [comment]
> I need to clarify something, to your program to run successfully I need the "auto" at the left up turn on right?

Yes. There's a setting in Genshin for auto-playing dialogue, make sure it's turned on.

**Comment by deka123A** [comment]
why i am asking is that, the auto function  waits all of the dialogue texts to be printed and then move to next, sometimes if just click you can skip entire dialogue without looking at it. I though your program does that + choose dialogue option.

**Comment by 1hubert** [comment]
> I though your program does that + choose dialogue option.

it should do that. something's wrong.

after running the script on my machine, turns out the Settings->Other->"Auto-Play Story" option needs to be off. sorry for confusing you earlier.

**Comment by deka123A** [comment]
it seems that it doesnt

only chooses dialogue option, and waits if there's none.

**Comment by 1hubert** [comment]
1) What's your screen resolution? (some people had the same issue when
running the game on an ultra wide monitor which has UI elements shifted in
comparison to 16:9 monitors)
2) Are you running the game in fullscreen? (you should)

śr., 17 sty 2024, 07:00 użytkownik deka123A ***@***.***>
napisał:

**Comment by deka123A** [comment]
2560 1440
16;9
fullscreen

**Comment by 1hubert** [comment]
thanks!

this friday i'll be visiting a friend who happens to have a monitor with
your screen resolution, will test the script on his pc and possibly release
a fix.

śr., 17 sty 2024, 10:53 użytkownik deka123A ***@***.***>
napisał:
