### ISSUE TITLE
Auto selects the bottom option, but not skips the text

### ISSUE THREAD

**Issue by SoyCbas** [1hubert/genshin-dialogue-autoskip#37]
I installed the script succesfully, and picked my resolution also apparently succesfully, but the text never skips, just the selection boxes.

https://github.com/1hubert/genshin-dialogue-autoskip/assets/131220704/d4f205b3-dd78-4a54-8eb6-ef2288d51494

Also I'm kinda stupid for this coding things so if you need more info just ask or feel free to insult me if I'm being an idiot :).

Using 1366x768 screen
Crappy out of date Hp laptop 
Genshin Impact Ver 4.5
Crappy NPC from Liyue
Freshly installed python  3.12.2
Auto Play Off from settings
Running from .bat as admin

**Comment by 1hubert** [comment]
it seems like your "auto play on/off" icon in the top-left corner of your video footage is white, which is unexpected as it used to be orangeish and judging from youtube videos like [this](https://www.youtube.com/watch?v=1kcba7ZYT_o) there wasn't any official change.

try changing [line 215](https://github.com/1hubert/genshin-dialogue-autoskip/blob/89c86207f780e68a6078704596a943036980b687/autoskip_dialogue.py#L125) in `autoskip_dialogue.py` to this:
```python
return pixel(PLAYING_ICON_X, PLAYING_ICON_Y) == (255, 255, 255)
```

**Comment by SoyCbas** [comment]
Hi, now I understood the mistake, and yup, the problem was the colors of the button. At first i tried to use 255 255 255 and it did go crazy in the loading screen, so then I used MsPaint to know the RGB values of the button, and change them according to the color of the button.
![Captura](https://github.com/1hubert/genshin-dialogue-autoskip/assets/131220704/339e0489-dbd1-4897-b08d-657a0b7ae4ed)
 
`return pixel(PLAYING_ICON_X, PLAYING_ICON_Y) == (236, 229, 216)`

Changing the line to that color fixed the problem. Thank you!

**Comment by 1hubert** [comment]
that's great and very clever of you! 🎉🎉 i'm glad you figured it out, and
thank you for describing the exact steps you took and providing the exact
rgb values!! i'll check if the colors on my end changed too, and if they
did will update the script.

pt., 15 mar 2024, 18:24 użytkownik SoyCbas ***@***.***>
napisał:

**Comment by SoyCbas** [comment]
Apparently there is something to do with changing the resolution in the game that's weird, so for example I was using a lower resolution config with alt+enter to "force" the game to fullscreen (using a lower 16:9 resolution to fill the entire screen [also the menu doesn't change it's size  too much if you ask]) but when I did that the script didn't skip the text, such as before, and I checked it's RGB colors again. They're a little bit different so the script didn't work. 

![Sin título](https://github.com/1hubert/genshin-dialogue-autoskip/assets/131220704/429f7c41-7728-4085-9952-0152a2cc2fc3)

This only happens when change the resolution to another different to the primary monitor even if it's just by a few pixels, so if you're running the game with the original screen res that the game gives you, then there shouldn't be any problems and the colors are the same as in the script. But if you change the screen resolution the colors change in the game and the script doesn't work so you need to edit that line to the colors that appear on the image.

`return pixel(PLAYING_ICON_X, PLAYING_ICON_Y) == (235, 228, 216)`

I don't know if the colors change on different screens, but if someone else is having this problem, his colors may differ a little bit.

I hope that this helps someone else having this problem, and again thank you!
