### ISSUE TITLE
Stuck on "RUNNING" 

### ISSUE THREAD

**Issue by ihatebray** [1hubert/genshin-dialogue-autoskip#38]
when running the script, it says running and nothing happens.

bottom option isn't selected and dialogue isnt skipped.

any help is appreciated, thank you!

EDIT: running as admin, everything i assume is downloaded correctly as i am not getting an error

resolution is set in env as 1920x1080

**Comment by MCafeAuto** [comment]
Same situation, how do I know if it is running in the game?

![Screenshot_1](https://github.com/1hubert/genshin-dialogue-autoskip/assets/169544454/1f8a7936-1c8e-44a9-83e4-05470c0f0edd)
