### ISSUE TITLE
ModuleNotFoundError: No module named 'vgamepad

### ISSUE THREAD

**Issue by Zotq** [1hubert/genshin-dialogue-autoskip#6]
When you run the .bat file as admin it throws an error "ModuleNotFoundError: No module named 'vgamepad"
![image](https://user-images.githubusercontent.com/88341255/236615608-48df3464-9162-4631-8cfc-ed275d9a78cc.png)

**Comment by 1hubert** [comment]
Hello 👋

The vgamepad module is currently required to run the script regardless if you use keyboard+mouse or a DS4 controller.

Install it using pip (Python Package Manager):
`pip install vgamepad`

You might also need to install pyautogui:
`pip install pyautogui`

Sorry for not making this clear in the readme!

**Comment by 1hubert** [comment]
Let me know if that fixed your issue

**Comment by Zotq** [comment]
![image](https://user-images.githubusercontent.com/88341255/236628494-3e1430d5-4df3-478b-b509-afdd13681a7b.png)

its running now,but still it doesn't skip dialogue,how do i make it work?

**Comment by Zotq** [comment]
ok i made it work,i suppose we have to click the "auto play" button every time a dialogue scene happens.

**Comment by 1hubert** [comment]
There's a setting in Genshin for auto-playing dialogue, make sure it's turned on.
